global using Application.Client;
global using Application.Core;
global using Application;
global using FluentValidation;
global using Mapster;
global using Microsoft.AspNetCore.Mvc;
global using Scalar.AspNetCore;
global using System.Net;
global using System.Text.Json;